### ISSUE TITLE
"Cannot read property 'text' of undefined" error

### ISSUE THREAD

**Issue by brivadeneira** [goto-bus-stop/wikibattle#85]
I was on a winning streak when all of the sudden:

Cannot read property 'text' of undefined
undefined

TypeError: Cannot read property 'text' of undefined
    at load (/home/wikibattle/.npm/prefix/lib/node_modules/wikibattle/src/wiki.js:110:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)

great game! 

With a couple of friends we were wanting to translate it to use wikepedia in spanish, any ideas of how we can start?

**Comment by goto-bus-stop** [comment]
hmm, do you remember which page you went to? my hunch is that it's not filtering some links correctly and you ended up accidentally visiting something that doesn't exist / is not the type of page wikibattle expects.

> With a couple of friends we were wanting to translate it to use wikepedia in spanish, any ideas of how we can start?

I thought about making it multilingual, it would be really nice. Right now WikiBattle is using a user-compiled list of popular articles so that you don't always go from tiny towns that you've never heard of to other tiny towns, I'm not sure if something like that exists for other languages :(
